### PR TITLE
Render output via fieldtype so this works for Lister results and Page list custom labels.

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by adrianbj** [comment]
Hey @Toutouwai - let me know your thoughts on this. I made the change because the current version doesn't render for Lister results or in the main page tree if you use the field to show info in a custom page label.

I have been using: http://modules.processwire.com/modules/fieldtype-runtime-markup/ but I find yours cleaner and simpler.

**Comment by adrianbj** [comment]
Also, just noticed that the field was creating a database table which is unnecessary. I basically stole the required methods from the FieldtypeRuntimeMarkup module for this.

**Comment by Toutouwai** [comment]
Thanks Adrian, will give this some thought and come back to it later.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I am using in production and so far it's working great.

**Comment by Toutouwai** [comment]
Hi @adrianbj,

Could you please try my recent commit to this pull request branch and let me know if it works for you?

I simplified the render() method and added a markupValue() method. That allows for a config option to disable Lister column rendering (and also allow hooking if the Lister rendering needs some special treatment). 

Most of the cases I'm using this Fieldtype for involve large rendered areas that would make a mess of the Lister, so I wanted a way to prevent such fields from rendering in the Lister in case a curious editor tried to add the field as a column.

**Comment by adrianbj** [comment]
@Toutouwai - new version seems to work great - thanks for the improvements. I think this is good to go live when you're ready.

Do you plan on publishing this in the modules directory?

**Comment by Toutouwai** [comment]
Thanks, have merged.
I wasn't planning on adding it to the directory because it's so similar to Kongondo's module.

**Comment by adrianbj** [comment]
> I wasn't planning on adding it to the directory because it's so similar to Kongondo's module.

I would contact him about it though - it doesn't sound like he has much time to maintain it anymore. I know his dev branch lets you use files for the render code, but the current stable doesn't and it's so much nicer being able to version that so I think it's really important.

Anyway, up to you, but he might be happy to have one less thing to maintain?

**Pull request merged**
